TIDAL: http://www.bio.brandeis.edu/laulab/Tidal_Fly/Tidal_Fly_v1Archive20150930.zip
TIDAL_ANNO: https://github.com/laulabbrandeis/TIDAL/raw/master/annotation.tar.gz

# sample assignments
SCRNA_GROUPS:
  larval-w1118-testes:
    - larval-testes-01
    - larval-testes-02
    - larval-testes-03
