# alignment options
GENOME_FASTA: /projects/genetics/ellison_lab/genomes/dna/masked/dmel-all-chromosome-r6.22.fasta.masked
TRANSPOSON_FASTA: /projects/genetics/ellison_lab/genomes/dna/masked/dmel_repbase_lib.fasta
GENE_GTF: ftp://ftp.flybase.net/releases/FB2018_03/dmel_r6.22/gtf/dmel-all-r6.22.gtf.gz
HETCHROM_FASTA: /scratch/mal456/hetchrom_dmel_scaffold2_V5.fasta
HETCHROM_GTF: /scratch/mal456/hetchrom_dmel_scaffold2_V5.gtf
TIDAL: http://www.bio.brandeis.edu/laulab/Tidal_Fly/Tidal_Fly_v1Archive20150930.zip
TIDAL_ANNO: https://github.com/laulabbrandeis/TIDAL/raw/master/annotation.tar.gz
DISALLOW_GENE_TYPES: [tRNA, rRNA]
CELLRANGER_VERSION: 3.1.0
CELLRANGER_MKREF_MEM: 16000
CELLRANGER_COUNT_MEM: 128000
CELLRANGER_COUNT_CPUS: 64
FASTERQDUMP_MEM: 16000
SHORTSTACK_MEM: 24000

# scanpy options
FBGNS: 'ftp://ftp.flybase.org/releases/FB2020_01/precomputed_files/genes/fbgn_annotation_ID_fb_2020_01.tsv.gz'
LARVAL_TESTIS_MARKERS: 'resources/larval-testis-markers.txt'
RANDOM_SEED: 2021
MITO_CUTOFF: 0.05 # 0.05
MAX_GENES: 5000 # 5000
GENE_MIN: 250 # 250
GENE_MIN_COUNT: 3 # 1
GENE_MIN_CELLS: 3 # 3
MAX_SCALE: 20 # set to arbitrarily huge number for no capping
N_NEIGHBORS: 25 # 20
N_PCS_FOR_NEIGHBORS: 15 # 15
UMAP_SPREAD: 1 #1
UMAP_MIN_DIST: 0.1 #0.1
LEIDEN_RESOLUTION: 0.35 #0.4
REGRESS_OUT:
  - S_score
  - G2M_score
  - percent_mito

# GEP option
MAX_SCALE_ICA: 10
QVAL_ICA: 0.005
COMPS_ICA: 90
REPS_ICA: 100
CUTOFF_APPROACH_ICA: 1 # 1 for keeping component together, 2 for splitting genes by above/below median signal
OUTLIER_FILT_KNN_ICA: 5 # robust to this
OUTLIER_MAX_DIST_ICA: 1000
ONT_GRID: BP
ONTS: [BP,MF,CC]
TOPGO_NODES: 100
GRID_MIN_QVAL: 0.005
GRID_MAX_QVAL: 0.1
GRID_STEP_QVAL: 2
GRID_MIN_COMPS: 20
GRID_MAX_COMPS: 120
GRID_STEP_COMPS: 10
GRID_REPS: 100
GRID_OVERALL_REPS: 3



# sample assignments
SCRNA_GROUPS:
  larval-w1118-testes:
    - larval-testes-01
    - larval-testes-02
    - larval-testes-03

RNASEQ_GROUPS:
  hsBam-rna:
    - RNA_seq_bam_mutant_rep1
    - RNA_seq_bam_mutant_rep2
    - RNA_seq_48hrPHS_rep1
    - RNA_seq_48hrPHS_rep2
    - RNA_seq_72hrPHS_rep1
    - RNA_seq_72hrPHS_rep2
    - RNA_seq_aly_mutant_rep1
    - RNA_seq_aly_mutant_rep2
